-- Tabla para gestionar ejercicios con enlaces de Google Drive
CREATE TABLE public.ejercicios (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  categoria text NOT NULL DEFAULT 'general'::text,
  musculo_principal text NOT NULL,
  musculos_secundarios text[],
  nivel_dificultad text NOT NULL DEFAULT 'principiante'::text,
  enlace_video text NOT NULL, -- URL de Google Drive
  duracion_minutos numeric,
  equipamiento text[],
  instrucciones text,
  consejos text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by bigint, -- ID del entrenador que creó el ejercicio
  activo boolean DEFAULT true,
  
  CONSTRAINT ejercicios_pkey PRIMARY KEY (id),
  CONSTRAINT ejercicios_nombre_key UNIQUE (nombre),
  CONSTRAINT ejercicios_nivel_check CHECK (nivel_dificultad IN ('principiante', 'intermedio', 'avanzado')),
  CONSTRAINT ejercicios_categoria_check CHECK (categoria IN ('cardio', 'fuerza', 'flexibilidad', 'funcional', 'general'))
) TABLESPACE pg_default;

-- Índices para mejorar rendimiento
CREATE INDEX idx_ejercicios_categoria ON public.ejercicios USING btree (categoria);
CREATE INDEX idx_ejercicios_musculo ON public.ejercicios USING btree (musculo_principal);
CREATE INDEX idx_ejercicios_nivel ON public.ejercicios USING btree (nivel_dificultad);
CREATE INDEX idx_ejercicios_activo ON public.ejercicios USING btree (activo);

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para actualizar updated_at
CREATE TRIGGER update_ejercicios_updated_at 
    BEFORE UPDATE ON public.ejercicios 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Política de seguridad (RLS) - opcional
ALTER TABLE public.ejercicios ENABLE ROW LEVEL SECURITY;

-- Permitir lectura a todos los usuarios autenticados
CREATE POLICY "Ejercicios son visibles para usuarios autenticados" ON public.ejercicios
    FOR SELECT USING (auth.role() = 'authenticated');

-- Permitir inserción y edición solo a entrenadores
CREATE POLICY "Solo entrenadores pueden crear ejercicios" ON public.ejercicios
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Solo entrenadores pueden editar ejercicios" ON public.ejercicios
    FOR UPDATE USING (auth.uid() IS NOT NULL);