-- ============================================
-- ESQUEMA DE BASE DE DATOS PARA RUTINAS
-- ============================================
-- Ejecutar este SQL en Supabase SQL Editor

-- 1. TABLA: rutinas
-- Almacena las rutinas de entrenamiento creadas por entrenadores
CREATE TABLE IF NOT EXISTS public.rutinas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT NULL,
  objetivo TEXT NULL DEFAULT ''::TEXT,
  duracion_semanas NUMERIC NULL DEFAULT 4,
  nivel_dificultad TEXT NOT NULL DEFAULT 'principiante'::TEXT,
  created_by BIGINT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  activo BOOLEAN NULL DEFAULT true,
  
  CONSTRAINT rutinas_pkey PRIMARY KEY (id),
  CONSTRAINT rutinas_nombre_key UNIQUE (nombre),
  CONSTRAINT rutinas_nivel_check CHECK (
    nivel_dificultad = ANY (
      ARRAY[
        'principiante'::TEXT,
        'intermedio'::TEXT,
        'avanzado'::TEXT
      ]
    )
  )
) TABLESPACE pg_default;

-- Índices para rutinas
CREATE INDEX IF NOT EXISTS idx_rutinas_nivel ON public.rutinas USING btree (nivel_dificultad) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_activo ON public.rutinas USING btree (activo) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_created_by ON public.rutinas USING btree (created_by) TABLESPACE pg_default;

-- Trigger para actualizar updated_at en rutinas
CREATE TRIGGER update_rutinas_updated_at 
BEFORE UPDATE ON rutinas 
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- 2. TABLA: rutinas_ejercicios
-- Relación entre rutinas y ejercicios, con detalles de ejecución
CREATE TABLE IF NOT EXISTS public.rutinas_ejercicios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rutina_id BIGINT NOT NULL,
  ejercicio_id BIGINT NOT NULL,
  orden INTEGER NOT NULL DEFAULT 1,
  series INTEGER NULL DEFAULT 3,
  repeticiones TEXT NULL DEFAULT '10-12',
  descanso_segundos INTEGER NULL DEFAULT 60,
  notas TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  
  CONSTRAINT rutinas_ejercicios_pkey PRIMARY KEY (id),
  CONSTRAINT rutinas_ejercicios_rutina_fk FOREIGN KEY (rutina_id) 
    REFERENCES public.rutinas(id) ON DELETE CASCADE,
  CONSTRAINT rutinas_ejercicios_ejercicio_fk FOREIGN KEY (ejercicio_id) 
    REFERENCES public.ejercicios(id) ON DELETE CASCADE,
  CONSTRAINT rutinas_ejercicios_unique UNIQUE (rutina_id, ejercicio_id, orden)
) TABLESPACE pg_default;

-- Índices para rutinas_ejercicios
CREATE INDEX IF NOT EXISTS idx_rutinas_ejercicios_rutina ON public.rutinas_ejercicios USING btree (rutina_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_ejercicios_ejercicio ON public.rutinas_ejercicios USING btree (ejercicio_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_ejercicios_orden ON public.rutinas_ejercicios USING btree (rutina_id, orden) TABLESPACE pg_default;

-- 3. TABLA: rutinas_clientes
-- Asignación de rutinas a clientes con seguimiento
CREATE TABLE IF NOT EXISTS public.rutinas_clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rutina_id BIGINT NOT NULL,
  cliente_id BIGINT NOT NULL,
  fecha_asignacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  fecha_inicio DATE NULL,
  fecha_fin DATE NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente'::TEXT,
  progreso NUMERIC NULL DEFAULT 0,
  notas TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  
  CONSTRAINT rutinas_clientes_pkey PRIMARY KEY (id),
  CONSTRAINT rutinas_clientes_rutina_fk FOREIGN KEY (rutina_id) 
    REFERENCES public.rutinas(id) ON DELETE CASCADE,
  CONSTRAINT rutinas_clientes_cliente_fk FOREIGN KEY (cliente_id) 
    REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT rutinas_clientes_estado_check CHECK (
    estado = ANY (
      ARRAY[
        'pendiente'::TEXT,
        'en_progreso'::TEXT,
        'completada'::TEXT,
        'pausada'::TEXT,
        'cancelada'::TEXT
      ]
    )
  ),
  CONSTRAINT rutinas_clientes_unique UNIQUE (rutina_id, cliente_id, fecha_asignacion)
) TABLESPACE pg_default;

-- Índices para rutinas_clientes
CREATE INDEX IF NOT EXISTS idx_rutinas_clientes_rutina ON public.rutinas_clientes USING btree (rutina_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_clientes_cliente ON public.rutinas_clientes USING btree (cliente_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_clientes_estado ON public.rutinas_clientes USING btree (estado) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_rutinas_clientes_fecha_inicio ON public.rutinas_clientes USING btree (fecha_inicio) TABLESPACE pg_default;

-- Trigger para actualizar updated_at en rutinas_clientes
CREATE TRIGGER update_rutinas_clientes_updated_at 
BEFORE UPDATE ON rutinas_clientes 
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- COMENTARIOS DE DOCUMENTACIÓN
-- ============================================

COMMENT ON TABLE public.rutinas IS 'Rutinas de entrenamiento creadas por entrenadores';
COMMENT ON TABLE public.rutinas_ejercicios IS 'Relación entre rutinas y ejercicios con detalles de ejecución (series, reps, descanso)';
COMMENT ON TABLE public.rutinas_clientes IS 'Asignación de rutinas a clientes con fechas y seguimiento de progreso';

COMMENT ON COLUMN public.rutinas.duracion_semanas IS 'Duración estimada de la rutina en semanas';
COMMENT ON COLUMN public.rutinas_ejercicios.orden IS 'Orden de ejecución del ejercicio dentro de la rutina';
COMMENT ON COLUMN public.rutinas_ejercicios.repeticiones IS 'Rango de repeticiones (ej: "10-12", "15", "hasta fallo")';
COMMENT ON COLUMN public.rutinas_clientes.progreso IS 'Porcentaje de progreso (0-100)';
COMMENT ON COLUMN public.rutinas_clientes.estado IS 'Estado actual: pendiente, en_progreso, completada, pausada, cancelada';

-- ============================================
-- PERMISOS RLS (Row Level Security) - OPCIONAL
-- ============================================
-- Descomenta si usas RLS en Supabase

-- ALTER TABLE public.rutinas ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.rutinas_ejercicios ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.rutinas_clientes ENABLE ROW LEVEL SECURITY;

-- Política para que entrenadores vean sus rutinas
-- CREATE POLICY "Entrenadores ven sus rutinas" ON public.rutinas
--   FOR SELECT USING (auth.uid() = created_by);

-- Política para que clientes vean sus rutinas asignadas
-- CREATE POLICY "Clientes ven sus rutinas" ON public.rutinas_clientes
--   FOR SELECT USING (auth.uid() = cliente_id);
