import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { 
  arrowBackOutline, 
  arrowBack, 
  arrowForward, 
  personOutline, 
  fitnessOutline, 
  medicalOutline, 
  checkmarkCircleOutline, 
  checkmarkCircle, 
  checkmark, 
  logIn,
  logOutOutline,
  personCircleOutline,
  personCircle,
  mailOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  person,
  fitness,
  medical,
  arrowForwardOutline,
  chevronForward,
  chevronBack,
  alert,
  alertCircle,
  alertCircleOutline,
  closeCircle,
  closeCircleOutline,
  informationCircle,
  informationCircleOutline,
  warningOutline,
  warning,
  home,
  homeOutline,
  settings,
  settingsOutline,
  menu,
  menuOutline,
  pencil,
  pencilOutline,
  trash,
  trashOutline,
  createOutline,
  create,
  heart,
  heartOutline,
  body,
  bodyOutline,
  addCircleOutline,
  refresh,
  refreshOutline,
  close,
  closeOutline,
  barbellOutline,
  barbell,
  timeOutline,
  time,
  personAddOutline,
  personAdd,
  playCircle,
  playCircleOutline,
  add,
  addOutline,
  listOutline,
  list,
  sadOutline,
  sad,
  calendarOutline,
  calendar,
  documentTextOutline,
  documentText,
  trophyOutline,
  trophy,
  repeatOutline,
  repeat,
  videocamOffOutline,
  videocamOff,
  restaurantOutline,
  restaurant,
  flash,
  flashOutline,
  people,
  peopleOutline,
  analytics,
  analyticsOutline,
  shieldCheckmark,
  shieldCheckmarkOutline,
  chevronUp,
  chevronDown
} from 'ionicons/icons';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

// Registrar iconos (todos los necesarios para el proyecto)
addIcons({
  'arrow-back-outline': arrowBackOutline,
  'arrow-back': arrowBack,
  'arrow-forward': arrowForward,
  'arrow-forward-outline': arrowForwardOutline,
  'person-outline': personOutline,
  'person': person,
  'fitness-outline': fitnessOutline,
  'fitness': fitness,
  'medical-outline': medicalOutline,
  'medical': medical,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'checkmark-circle': checkmarkCircle,
  'checkmark': checkmark,
  'person-circle-outline': personCircleOutline,
  'person-circle': personCircle,
  'mail-outline': mailOutline,
  'lock-closed-outline': lockClosedOutline,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'chevron-forward': chevronForward,
  'chevron-back': chevronBack,
  'alert': alert,
  'alert-circle': alertCircle,
  'alert-circle-outline': alertCircleOutline,
  'close-circle': closeCircle,
  'close-circle-outline': closeCircleOutline,
  'information-circle': informationCircle,
  'information-circle-outline': informationCircleOutline,
  'warning-outline': warningOutline,
  'warning': warning,
  'home': home,
  'home-outline': homeOutline,
  'settings': settings,
  'settings-outline': settingsOutline,
  'menu': menu,
  'menu-outline': menuOutline,
  'log-in': logIn,
  'log-out-outline': logOutOutline,
  'pencil': pencil,
  'pencil-outline': pencilOutline,
  'trash': trash,
  'trash-outline': trashOutline,
  'create-outline': createOutline,
  'create': create,
  'heart': heart,
  'heart-outline': heartOutline,
  'body': body,
  'body-outline': bodyOutline,
  'add-circle-outline': addCircleOutline,
  'refresh': refresh,
  'refresh-outline': refreshOutline,
  'close': close,
  'close-outline': closeOutline,
  'barbell-outline': barbellOutline,
  'barbell': barbell,
  'time-outline': timeOutline,
  'time': time,
  'person-add-outline': personAddOutline,
  'person-add': personAdd,
  'play-circle': playCircle,
  'play-circle-outline': playCircleOutline,
  'add': add,
  'add-outline': addOutline,
  'list-outline': listOutline,
  'list': list,
  'sad-outline': sadOutline,
  'sad': sad,
  'calendar-outline': calendarOutline,
  'calendar': calendar,
  'document-text-outline': documentTextOutline,
  'document-text': documentText,
  'trophy-outline': trophyOutline,
  'trophy': trophy,
  'repeat-outline': repeatOutline,
  'repeat': repeat,
  'videocam-off-outline': videocamOffOutline,
  'videocam-off': videocamOff,
  'restaurant-outline': restaurantOutline,
  'restaurant': restaurant,
  'flash': flash,
  'flash-outline': flashOutline,
  'people': people,
  'people-outline': peopleOutline,
  'analytics': analytics,
  'analytics-outline': analyticsOutline,
  'shield-checkmark': shieldCheckmark,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'chevron-up': chevronUp,
  'chevron-down': chevronDown
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
  ],
});
